### ISSUE TITLE
Release dependency issues 

### ISSUE THREAD

**Issue by m-abboud** [radkovo/Pdf2Dom#15]
Opening an issue for this for discussion/status update since pull request where we were talking about this is closed.

So FontVerter and GfxAssert should be added to maven central,  I opened tickets with Sonatype today to get them setup and think I've got all the maven central requirements met. So if Sonatype responds on the weekends it should be done by then.

**Comment by m-abboud** [comment]
Also have FontVerter up on JCenter already (which is the default repo for android studio now)

**Comment by radkovo** [comment]
I have released a new version of Pdf2Dom (mentioned you in [credits](http://cssbox.sourceforge.net/pdf2dom/credits.php)). All the dependencies seem to be ok now.
