### ISSUE TITLE
FontVerter 1.2.18 depends on maven-reflections which has missing dependency

### ISSUE THREAD

**Issue by borick** [radkovo/Pdf2Dom#20]
from my local maven build debug output

[DEBUG]    net.sf.cssbox:pdf2dom:jar:1.6:compile
[DEBUG]       net.sf.cssbox:cssbox:jar:4.12:compile
[DEBUG]          net.sourceforge.nekohtml:nekohtml:jar:1.9.22:compile
[DEBUG]          xerces:xercesImpl:jar:2.11.0:compile
[DEBUG]          xml-apis:xml-apis:jar:1.4.01:compile
[DEBUG]          net.sf.cssbox:jstyleparser:jar:1.23:compile
[DEBUG]             org.antlr:antlr-runtime:jar:3.5.2:compile
[DEBUG]             org.unbescape:unbescape:jar:1.1.3.RELEASE:compile
[DEBUG]       net.mabboud.fontverter:FontVerter:jar:1.2.18:compile
[DEBUG]          org.reflections:reflections-maven:jar:0.9.9-RC2:compile
[DEBUG]             org.reflections:reflections:jar:0.9.9-RC2:compile
[DEBUG]                com.google.code.findbugs:annotations:jar:2.0.1:compile
[DEBUG]                dom4j:dom4j:jar:1.6.1:compile
[DEBUG]             org.jfrog.maven.annomojo:maven-plugin-anno:jar:1.4.1:compile
[DEBUG]             org.jfrog.jade.plugins.common:jade-plugin-common:jar:1.3.8:compile

however jade-plugin-common is suddenly missing from the central repo

**Comment by borick** [comment]
actually not sure if the unicode issues are result of missing lib or not, since i believe I have restored the lib locally but, still getting those problems currently but may be result of something else unrelated to missing lib, not sure, will update if get more progress/info, thank you

**Comment by m-abboud** [comment]
Oh yeah bumped into that a while ago forgot to update Pdf2Dom for new FontVerter version.

Could you attach the PDF you mentioned that you're having wonky output with?

**Comment by borick** [comment]
@m-abboud sorry it was my problem, not writing file properly in UTF encoding so I edited my comment, only remaining issue I can find is the dependency, thank you :)

**Comment by m-abboud** [comment]
created pull request for this
@radkovo Should probably push new version of Pdf2Dom after you merge this as I think it's a critical bug.

 jade-plugin-common went missing for some people. IIRC it still worked on my machine when I tried to reproduce when I fixed it in FontVerter so won't happen for everyone I think though.
