### ISSUE TITLE
error loading font

### ISSUE THREAD

**Issue by 1289naveen** [radkovo/Pdf2Dom#26]
getting warning like
"WARN org.fit.pdfdom.FontTable - Error loading font 'FTBUET+Verdana-Bold' Message: FontVerter could not detect the input font's type. class java.io.IOException"
 is there any solution for this.
Thank you

**Comment by m-abboud** [comment]
What type of font is it? FontVerter only supports a limited number of font types. https://github.com/m-abboud/FontVerter. Also this issue should probably be in the FontVerter repository

**Comment by 1289naveen** [comment]
Ok Thanks abboud.
