### ISSUE TITLE
Pdfbox dependency security vulnerabilities

### ISSUE THREAD

**Issue by m-abboud** [radkovo/Pdf2Dom#33]
Just remembered I got an email from GitHub notifying me fontverter's pdfbox dependency has a vunrability. Pdf2dom has the same separate dependency entry for pdfbox as well so need to bump that and also fontverter version after it's bumped there as well. 

I'll try to remember to make a PR when I get home from work but making this issue in case I forget again..

**Comment by radkovo** [comment]
Thanks for reminder, I have updated it just now.
