### ISSUE TITLE
Maven not able to resolve dependencie cssbox 4.14-SNAPSHOT

### ISSUE THREAD

**Issue by noahholley** [radkovo/Pdf2Dom#34]
Resolution: Modify pom to install cssbox 4.14 instead.

**Comment by radkovo** [comment]
This is not a bug. Development version available in the git repo may depend on development versions of other libraries (snapshots). They are resolved just before a new release. You may obtain current cssbox from the git as well (`git clone` and `mvn install`) or use the solution you mention if it works for you.
