### ISSUE TITLE
embedfonts branch remaining work?

### ISSUE THREAD

**Issue by m-abboud** [radkovo/Pdf2Dom#7]
(More of a discussion item than an actual issue) 

So what remaining work is there for the embedfonts branch? From what I see it just needs adding conversion for the various non browser supported pdf font types?

I added support for bare CFF (PdfBox calls it Type1C I believe) in [my embedded-fonts-2 branch](https://github.com/m-abboud/Pdf2Dom/tree/embedded-fonts-2 ) and maybe going to start work on others and if I recall correctly bare CFF is the most common but maybe wishful thinking.

**Comment by radkovo** [comment]
This seems very nice. I just ended up with being unable to extract a font file that would be accepted by the browsers. Obviously some conversion is necessary but since I am not expert on fonts, I have given up for that moment. If your conversion works, I'll be pleased to merge your branch.

**Comment by radkovo** [comment]
Resolved by #8 and #10.
